<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Ally.Application</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<!-- Correct ProjectReference to Ally.Domain.csproj -->
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Core\Authentication\QueryHandler\" />
		<Folder Include="Core\Authentication\Query\" />
		<Folder Include="Core\Products\CommandHandler\" />
		<Folder Include="Core\Products\Command\" />
		<Folder Include="Core\Products\QueryHandler\" />
		<Folder Include="Core\Products\Query\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MediaTr" Version="12.2.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.8.1" />

	</ItemGroup>

</Project>
